language: r
sudo: true
cache: packages

before_install:
        - sudo add-apt-repository -y ppa:cran/imagemagick
        - sudo apt-get update
        - sudo apt-get install -y libmagick++-dev

r_github_packages: 
        - jinyizju/V.PhyloMaker
        - ropensci/magick
